interface TRAINING_CENTER {
  country_code: string;
  training_center_id: string;
  training_center_name: string;
  state_providence: string | null;
}

export const TRAINING_CENTERS: Array<TRAINING_CENTER> = [
  {
    country_code: "CAN",
    training_center_id: "BNR",
    training_center_name: "BAR NONE RANCHES",
    state_providence: "AB",
  },
  {
    country_code: "USA",
    training_center_id: "ABC",
    training_center_name: "ABRACADABRA FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ADR",
    training_center_name: "ADRIAN SOTO RACING STABLES",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ADS",
    training_center_name: "ADENA SPRINGS FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "AEF",
    training_center_name: "ANOTHER EPISODE FARM, INC.",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "AFT",
    training_center_name: "ANDOR FARM TRAINING CENTER",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "AHT",
    training_center_name: "ATLANTA HALL TRAINING CENTER",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "AKI",
    training_center_name: "AKINDALE TRAINING CENTER",
    state_providence: "NY",
  },
  {
    country_code: "USA",
    training_center_id: "ARI",
    training_center_name: "ARINDEL FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ASF",
    training_center_name: "ALL SEVEN FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ASH",
    training_center_name: "ASHWELL STABLES",
    state_providence: "PA",
  },
  {
    country_code: "USA",
    training_center_id: "ATC",
    training_center_name: "ASHWOOD TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "BDW",
    training_center_name: "BRIDLEWOOD FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "BEQ",
    training_center_name: "Burke Equine Training Center",
    state_providence: "NY",
  },
  {
    country_code: "USA",
    training_center_id: "BES",
    training_center_name: "BESILU STABLES",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "BKE",
    training_center_name: "BURKE TRAINING CENTER",
    state_providence: "UT",
  },
  {
    country_code: "USA",
    training_center_id: "BLF",
    training_center_name: "BOLO FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "BLK",
    training_center_name: "BLACKWOOD STABLES",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "BLT",
    training_center_name: "BRADFORD LANE TRAINING CENTER",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "BLV",
    training_center_name: "BELVOIR TRAINING CENTER",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "BNT",
    training_center_name: "BENTON TRAINING CENTER",
    state_providence: "LA",
  },
  {
    country_code: "USA",
    training_center_id: "BON",
    training_center_name: "BONITA FARM",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "BRM",
    training_center_name: "BREAKING MAIDENS FARM",
    state_providence: "AL",
  },
  {
    country_code: "USA",
    training_center_id: "BRS",
    training_center_name: "BURNS RACING STABLE",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "BTB",
    training_center_name: "BIGHEART THOROUGHBREDS",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "BTC",
    training_center_name: "BRAEBURN",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "BTF",
    training_center_name: "BOB TROUT FARM",
    state_providence: "MO",
  },
  {
    country_code: "USA",
    training_center_id: "BWC",
    training_center_name: "BLUEWATER CREEK FARM",
    state_providence: "AL",
  },
  {
    country_code: "USA",
    training_center_id: "CAA",
    training_center_name: "CASSE TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CAP",
    training_center_name: "CAPTAIN'S TRAINING CENTER",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "CBQ",
    training_center_name: "CHABBOQUESSET TRAINING CENTER",
    state_providence: "GA",
  },
  {
    country_code: "USA",
    training_center_id: "CBS",
    training_center_name: "COOL BREEZE STABLES",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "CBT",
    training_center_name: "CANYON BREEZE TRAINING CENTER",
    state_providence: "UT",
  },
  {
    country_code: "USA",
    training_center_id: "CBV",
    training_center_name: "CABIN VIEW FARM",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "CCE",
    training_center_name: "COPPER CITY EQUINE",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CCT",
    training_center_name: "THE TRAINING CENTER AT COPPER CROWNE",
    state_providence: "LA",
  },
  {
    country_code: "USA",
    training_center_id: "CDH",
    training_center_name: "CARDINAL HILL",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CDT",
    training_center_name: "CHURCHILL TRAINING",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "CFR",
    training_center_name: "CENTRAL FLORIDA RANCHES",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CGR",
    training_center_name: "CIRCLE G RANCH",
    state_providence: "OH",
  },
  {
    country_code: "USA",
    training_center_id: "CHM",
    training_center_name: "CHAMPAGNE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CIM",
    training_center_name: "CIMARRON FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CIR",
    training_center_name: "CIRCLE 8 TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "CLT",
    training_center_name: "COURTLANDT FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CM",
    training_center_name: "CLASSIC MILE",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CMB",
    training_center_name: "CUMBERLAND COUNTY FAIRGROUNDS",
    state_providence: "IL",
  },
  {
    country_code: "USA",
    training_center_id: "CMF",
    training_center_name: "CALUMET FARM TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "CNR",
    training_center_name: "CANYON ROAD TRAINING CENTER",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "CNS",
    training_center_name: "COLTS NECK STABLES",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "COF",
    training_center_name: "CITRA OAKS FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CRU",
    training_center_name: "CRUPI'S NEW CASTLE FARM, INC.",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CSB",
    training_center_name: "CASTLEBROOK TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CSS",
    training_center_name: "CIRCLE S FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CTS",
    training_center_name: "CLOUSTON TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "CTT",
    training_center_name: "CAIN'S THOROUGHBRED TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "CWS",
    training_center_name: "CROWN'S WAY SOUTH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "DBR",
    training_center_name: "DOUBLE D RANCH",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "DD",
    training_center_name: "DIAMOND D RANCH",
    state_providence: "TX",
  },
  {
    country_code: "USA",
    training_center_id: "DDF",
    training_center_name: "DOUBLE DIAMOND FARM AND TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "DDR",
    training_center_name: "DIAMOND D RANCH",
    state_providence: "TX",
  },
  {
    country_code: "USA",
    training_center_id: "DDT",
    training_center_name: "DERBY DAYS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "DER",
    training_center_name: "DERBY DREAMS TRAINING & EQUINE CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "DFF",
    training_center_name: "DEER FIELD FARM",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "DLF",
    training_center_name: "DRAGONS LYRE FARMS",
    state_providence: "TN",
  },
  {
    country_code: "USA",
    training_center_id: "DMC",
    training_center_name: "DMC TRAINING CENTER",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "DMT",
    training_center_name: "DOUBLE M TRAINING CENTER",
    state_providence: "AR",
  },
  {
    country_code: "USA",
    training_center_id: "DON",
    training_center_name: "DONIDA TRAINING CENTER",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "DOT",
    training_center_name: "DIAMOND OAK TRAINING CENTER",
    state_providence: "PA",
  },
  {
    country_code: "USA",
    training_center_id: "DRT",
    training_center_name: "DUNN RANCH TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "DTD",
    training_center_name: "DARE TO DREAM FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "DTR",
    training_center_name: "DELTA TRAINING CENTER",
    state_providence: "TX",
  },
  {
    country_code: "USA",
    training_center_id: "DWM",
    training_center_name: "DREAM WITH ME STABLES",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "EAS",
    training_center_name: "EASTLAND TRAINING CENTER",
    state_providence: "",
  },
  {
    country_code: "USA",
    training_center_id: "ECL",
    training_center_name: "ECLIPSE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ECR",
    training_center_name: "ELK CREEK RANCH",
    state_providence: "PA",
  },
  {
    country_code: "USA",
    training_center_id: "ECT",
    training_center_name: "EAST CAROLINA TRAINING CENTER",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "EDS",
    training_center_name: "ENDS WELL FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "EDT",
    training_center_name: "EMPRESS DOWNS TRAINING CENTER",
    state_providence: "GA",
  },
  {
    country_code: "USA",
    training_center_id: "EGL",
    training_center_name: "EAGLE ROCK DOWNS",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "EIS",
    training_center_name: "EISAMAN TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ELL",
    training_center_name: "ELLOREE TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "EME",
    training_center_name: "EMERALD PASTURES TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "EOF",
    training_center_name: "ENDSLEY OAK FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "EPF",
    training_center_name: "EAGLE POINT FARM",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "EPR",
    training_center_name: "EL PRIMERO TRAINING CENTER",
    state_providence: "TX",
  },
  {
    country_code: "USA",
    training_center_id: "EQL",
    training_center_name: "EQUELS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ETC",
    training_center_name: "ECLIPSE TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "EVR",
    training_center_name: "EVERGREEN TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "EVT",
    training_center_name: "EVANGELINE TRAINING CENTER",
    state_providence: "LA",
  },
  {
    country_code: "USA",
    training_center_id: "EWT",
    training_center_name: "EDDIE WOODS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "FBF",
    training_center_name: "FOX BROWN FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "FCL",
    training_center_name: "FAIRCLOTH TRAINING CENTER",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "FFM",
    training_center_name: "FOLK FARM",
    state_providence: "PA",
  },
  {
    country_code: "USA",
    training_center_id: "FID",
    training_center_name: "FIDELIA STABLES",
    state_providence: "PA",
  },
  {
    country_code: "USA",
    training_center_id: "FLF",
    training_center_name: "FAR LADY FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "FOL",
    training_center_name: "FOLSOM TRAINING CENTER",
    state_providence: "LA",
  },
  {
    country_code: "USA",
    training_center_id: "FPF",
    training_center_name: "FORT PLAINS FARM",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "FRF",
    training_center_name: "FRANKS FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "FRN",
    training_center_name: "FRONTERA TRAINING CENTER",
    state_providence: "NM",
  },
  {
    country_code: "USA",
    training_center_id: "FRO",
    training_center_name: "FROST TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "FXP",
    training_center_name: "FOX POINT FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GD",
    training_center_name: "GALWAY DOWNS",
    state_providence: "CA",
  },
  {
    country_code: "USA",
    training_center_id: "GDC",
    training_center_name: "GOOD CHANCE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GDF",
    training_center_name: "GARYDALE FARM TRAINING CENTER",
    state_providence: "VT",
  },
  {
    country_code: "USA",
    training_center_id: "GFT",
    training_center_name: "GOODWIN FARMS TRAINING CENTER",
    state_providence: "NY",
  },
  {
    country_code: "USA",
    training_center_id: "GHT",
    training_center_name: "GLEN HILL FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GLC",
    training_center_name: "GLOCKENBURG LLC",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GLF",
    training_center_name: "GREAT LAKES FAIR TRAINING FACILITY",
    state_providence: "MI",
  },
  {
    country_code: "USA",
    training_center_id: "GLM",
    training_center_name: "GOLDMARK",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GLP",
    training_center_name: "THE GALLOPS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GLS",
    training_center_name: "GOLDEN LEGACY STABLES",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GNN",
    training_center_name: "GUNN FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GOE",
    training_center_name: "GRAND OAKS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GPF",
    training_center_name: "GENUINE PLEASURE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "GRS",
    training_center_name: "GARRISON FARM",
    state_providence: "TN",
  },
  {
    country_code: "USA",
    training_center_id: "GTC",
    training_center_name: "GREENTREE TRAINING CENTER",
    state_providence: "NY",
  },
  {
    country_code: "USA",
    training_center_id: "GTW",
    training_center_name: "GATEWAY DOWNS",
    state_providence: "CO",
  },
  {
    country_code: "USA",
    training_center_id: "GVT",
    training_center_name: "GREEN VALLEY TRAINING CENTER",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "HAM",
    training_center_name: "HAMILTON COUNTY FAIR",
    state_providence: "IL",
  },
  {
    country_code: "USA",
    training_center_id: "HBH",
    training_center_name: "HUNTER BROOK HORSE FARM, INC.",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "HBS",
    training_center_name: "HIDDEN BROOK SOUTH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "HDR",
    training_center_name: "HARTLEY DERENZO TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "HDT",
    training_center_name: "H & D TRAINING CENTER",
    state_providence: "GA",
  },
  {
    country_code: "USA",
    training_center_id: "HER",
    training_center_name: "HERITAGE FARM TRAINING CENTER",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "HFF",
    training_center_name: "HUNT FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "HHC",
    training_center_name: "HURRICANE HALL TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "HHT",
    training_center_name: "HENNESSY HILL TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "HMP",
    training_center_name: "HORSEMAN'S PARK",
    state_providence: "NM",
  },
  {
    country_code: "USA",
    training_center_id: "HPC",
    training_center_name: "HORSE PLAZA TRAINING CENTER",
    state_providence: "OR",
  },
  {
    country_code: "USA",
    training_center_id: "HPP",
    training_center_name: "HORSE PLAZA TRAINING CENTER",
    state_providence: "OR",
  },
  {
    country_code: "USA",
    training_center_id: "HPT",
    training_center_name: "HIGHPOINT FARM AND TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "HRF",
    training_center_name: "HAWKINRIDGE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "HTC",
    training_center_name: "HARMONY TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "HTF",
    training_center_name: "HICKORY TREE FARM TRAINING CENTER",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "HTG",
    training_center_name: "HERITAGE PARK",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "HUF",
    training_center_name: "HUNTER FARM TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "HYT",
    training_center_name: "HYATT FARM AND TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "IAF",
    training_center_name: "IRISH ACRES FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ISA",
    training_center_name: "ISABELLA CO-EXPO TRAINING CENTER",
    state_providence: "MI",
  },
  {
    country_code: "USA",
    training_center_id: "ITC",
    training_center_name: "INFIELDS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "JDF",
    training_center_name: "JOE DAN FARM",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "JDM",
    training_center_name: "JDM TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "JHF",
    training_center_name: "JORDAN'S HORSE FARM",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "JMF",
    training_center_name: "JUDDMONTE FARM",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "JOU",
    training_center_name: "JOURNEYS END TRAINING CENTER",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "JUB",
    training_center_name: "JUBILEE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "JVR",
    training_center_name: "J V RANCH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "JWE",
    training_center_name: "JAYS WAY EQUESTRIAN CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "KFF",
    training_center_name: "KING FISHER TRAINING CENTER",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "KIK",
    training_center_name: "KICK START TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "KNF",
    training_center_name: "KINSMAN FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "LAZ",
    training_center_name: "LAZY E TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "LCT",
    training_center_name: "LEVY COUNTY TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "LGF",
    training_center_name: "LEGACY FARM",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "LIT",
    training_center_name: "LITTLE BROOK TRAINING CENTER",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "LMB",
    training_center_name: "LAMBHOLM SOUTH TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "LOF",
    training_center_name: "LONE OAK FARM",
    state_providence: "GA",
  },
  {
    country_code: "USA",
    training_center_id: "LVT",
    training_center_name: "LAKE VIEW TRAINING CENTER",
    state_providence: "OH",
  },
  {
    country_code: "USA",
    training_center_id: "MBF",
    training_center_name: "MCKATHAN BROTHERS FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "MBT",
    training_center_name: "MIDDLEBURG TRAINING CENTER",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "MCG",
    training_center_name: "MCGUIRE FARMS",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "MCU",
    training_center_name: "MCCUTCHEN TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "MER",
    training_center_name: "MERCURY EQUINE CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "MFT",
    training_center_name: "MCKATHAN FARM TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "MIH",
    training_center_name: "MIAMI HORSEMEN'S ASSOCIATION TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "MKT",
    training_center_name: "MACKABEN TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "MKY",
    training_center_name: "MASARKYTOWN TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "MME",
    training_center_name: "MARLYN MEADOWS",
    state_providence: "DE",
  },
  {
    country_code: "USA",
    training_center_id: "MOG",
    training_center_name: "MOMENT OF GLORY TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "MRT",
    training_center_name: "MARTINSVILLE FAIRGROUNDS",
    state_providence: "IL",
  },
  {
    country_code: "USA",
    training_center_id: "MRX",
    training_center_name: "MARGAUX FARM",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "MRY",
    training_center_name: "MERRYLAND FARM",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "MST",
    training_center_name: "MID SOUTH TRAINING",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "MTC",
    training_center_name: "MIDDLETOWN TRAINING CENTER",
    state_providence: "DE",
  },
  {
    country_code: "USA",
    training_center_id: "MWF",
    training_center_name: "MAYO WEST FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "MWT",
    training_center_name: "MIDWEST THOROUGHBREDS",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "NAD",
    training_center_name: "NAD AL SHEBA",
    state_providence: "",
  },
  {
    country_code: "USA",
    training_center_id: "NBS",
    training_center_name: "NIALL BRENNAN STABLES",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "NET",
    training_center_name: "NEW EPISODE TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "NEW",
    training_center_name: "NEW HORIZONS FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "NHF",
    training_center_name: "NEW HAVEN FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "NJF",
    training_center_name: "NELSON JONES FARMS AND TRAINING CENTER, INC.",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "NPR",
    training_center_name: "NAPIER'S TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "NTC",
    training_center_name: "NOBLES TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "NWF",
    training_center_name: "NEW FARM TRAINING CENTER",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "OAK",
    training_center_name: "OAKHURST THOROUGHBREDS TRAINING CENTER",
    state_providence: "OR",
  },
  {
    country_code: "USA",
    training_center_id: "OCF",
    training_center_name: "OKANAGAN COUNTY FAIRGROUNDS",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "OEC",
    training_center_name: "OAKRIDGE TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "OHC",
    training_center_name: "OCALA HORSE FARM COMPLEX",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "OJO",
    training_center_name: "OCALA JOCKEY CLUB TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "OKL",
    training_center_name: "OAKLEAF TRAINING CENTER",
    state_providence: "TX",
  },
  {
    country_code: "USA",
    training_center_id: "OLY",
    training_center_name: "OLYMPIC HILL TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "ORT",
    training_center_name: "ORTING TRAINING CENTER",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "OTF",
    training_center_name: "OCALA THOROUGHBRED FARMS",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "OVR",
    training_center_name: "OVERBROOK TRAINING CENTER",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "OWT",
    training_center_name: "OCALA RANCHES",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "OXF",
    training_center_name: "OXFORD TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PAY",
    training_center_name: "PAYSON PARK TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PBD",
    training_center_name: "PALM BEACH DOWNS",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PCF",
    training_center_name: "PINK CROWN FARMS",
    state_providence: "TX",
  },
  {
    country_code: "USA",
    training_center_id: "PDA",
    training_center_name: "PADUA TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PEG",
    training_center_name: "PEGASUS THOROUGHBRED TRAINING CENTER",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "PER",
    training_center_name: "PERFENICK FARM",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "PJT",
    training_center_name: "PAUL JONES TRAINING CENTER, TULAROSA",
    state_providence: "NM",
  },
  {
    country_code: "USA",
    training_center_id: "PMM",
    training_center_name: "PALM MEADOWS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PNS",
    training_center_name: "PENINSULA FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PPX",
    training_center_name: "PLEASANT PASTURE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PRD",
    training_center_name: "PARADISE STABLES, LLC",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "PRT",
    training_center_name: "PREMIER THOROUGHBREDS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "PTT",
    training_center_name: "PALMETTO THOROUGHBRED TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "PVF",
    training_center_name: "POND VIEW FARM",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "PYN",
    training_center_name: "PAYTON TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "QWF",
    training_center_name: "QUIET WOMAN FARM TRAINING CENTER",
    state_providence: "NY",
  },
  {
    country_code: "USA",
    training_center_id: "QWS",
    training_center_name: "QUIET WOMAN FARM SOUTH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "RBT",
    training_center_name: "RED BOB TRAINING FACILITY",
    state_providence: "MI",
  },
  {
    country_code: "USA",
    training_center_id: "RCE",
    training_center_name: "RACING EDGE TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "RDE",
    training_center_name: "RED EARTH TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "REB",
    training_center_name: "REBER RANCH TRAINING TRACK",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "RIG",
    training_center_name: "RIGBIE FARM",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "RIS",
    training_center_name: "RISING SUN FARM",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "RKV",
    training_center_name: "ROCKY VALLEY",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "RMF",
    training_center_name: "R & M FARMS",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "RMT",
    training_center_name: "ROSS MEADOWS",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "ROF",
    training_center_name: "RED OAK FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "RQH",
    training_center_name: "RQHS Mile",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "RSD",
    training_center_name: "RIVERSIDE DOWNS",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "SAB",
    training_center_name: "SABINE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SAM",
    training_center_name: "SAM-SON FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SBA",
    training_center_name: "STONEBRIDGE ANNEX",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SBF",
    training_center_name: "SHADYBROOK FARM, INC.",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SBG",
    training_center_name: "STONEBRIDGE TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SBT",
    training_center_name: "SOUTHERN BREEZE TRAINING CTR",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SCH",
    training_center_name: "SCHULTZ RACING STABLE",
    state_providence: "CO",
  },
  {
    country_code: "USA",
    training_center_id: "SCN",
    training_center_name: "SCANLON TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SCT",
    training_center_name: "SANDERS CREEK TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "SER",
    training_center_name: "SERENDIPITY FARM",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "SFC",
    training_center_name: "SOUTH FLORIDA TROTTING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SFT",
    training_center_name: "SUNNYSIDE FARM TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SGC",
    training_center_name: "STARTING GATE TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SGF",
    training_center_name: "SAGAMORE FARM",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "SHF",
    training_center_name: "SILVERTON HILL FARM",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "SHS",
    training_center_name: "SOVEREIGN HILL STABLES",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "SIL",
    training_center_name: "SILVER STAR EQUINE CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "SKF",
    training_center_name: "STRICKLAND FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SKL",
    training_center_name: "SKY'S THE LIMIT",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SKY",
    training_center_name: "SKYLIGHT TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "SLF",
    training_center_name: "SOLERA FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SLH",
    training_center_name: "SILVERLEAF HILLS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SLT",
    training_center_name: "STOCKLAND",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "SOT",
    training_center_name: "SILVER OAKS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SPC",
    training_center_name: "STARTING POINT TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SSS",
    training_center_name: "STANLEY STABLES",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "SST",
    training_center_name: "SUNRISE STABLE SOUTH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "STB",
    training_center_name: "STONEBRIDGE FARM",
    state_providence: "NY",
  },
  {
    country_code: "USA",
    training_center_id: "STC",
    training_center_name: "SALLISAW EQUINE TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "STF",
    training_center_name: "STARSFELL FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "STO",
    training_center_name: "STONY OAK TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "STR",
    training_center_name: "SINATRA THOROUGHBRED RACING",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "STS",
    training_center_name: "SIESTA SUN TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "STT",
    training_center_name: "STONESTREET TRAINING LLC",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "STU",
    training_center_name: "STUTTS STABLE",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "STW",
    training_center_name: "STONEWALL FARM",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "SUM",
    training_center_name: "SUMMERFIELD TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "SUT",
    training_center_name: "SUTHERLAND FARM",
    state_providence: "ID",
  },
  {
    country_code: "USA",
    training_center_id: "SVR",
    training_center_name: "SILVER SPRINGS TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "SWH",
    training_center_name: "SWEETWATER HORSE TRACK AND TRAINING CENTER",
    state_providence: "GA",
  },
  {
    country_code: "USA",
    training_center_id: "SWT",
    training_center_name: "SANDY WOODS TRAINING CENTER",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "SYC",
    training_center_name: "SYCAMORE TRAINING CENTER",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "SYL",
    training_center_name: "SYLMAR FARM",
    state_providence: "PA",
  },
  {
    country_code: "USA",
    training_center_id: "TAP",
    training_center_name: "TAPETA FARM",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "TAT",
    training_center_name: "T & A TRAINING CENTER",
    state_providence: "TN",
  },
  {
    country_code: "USA",
    training_center_id: "TBR",
    training_center_name: "TB RACING",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "TCC",
    training_center_name: "THOROUGHBRED CHAMPIONS TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "TCS",
    training_center_name: "THE CROSSROADS SOUTH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "TDD",
    training_center_name: "THREE DIAMONDS TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "TDT",
    training_center_name: "TRAVIS DURR TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "THL",
    training_center_name: "THORNHILL FARM",
    state_providence: "PA",
  },
  {
    country_code: "USA",
    training_center_id: "THT",
    training_center_name: "TARHEEL TRAINING CENTER",
    state_providence: "NC",
  },
  {
    country_code: "USA",
    training_center_id: "TOO",
    training_center_name: "TOOLE'S TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "TRE",
    training_center_name: "TREMONTON",
    state_providence: "UT",
  },
  {
    country_code: "USA",
    training_center_id: "TRT",
    training_center_name: "THUNDER RANCH TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "TSF",
    training_center_name: "TRACKSIDE FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "TST",
    training_center_name: "TRUE SOUTH TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "TWR",
    training_center_name: "TEAM WORK RACING",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "VAN",
    training_center_name: "VANATTA TRACK AND TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "VHT",
    training_center_name: "VICTORY HAVEN TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "VIN",
    training_center_name: "VINERY STABLE",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "VQF",
    training_center_name: "VICTORY QUEST FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "VTC",
    training_center_name: "VICTORIA TRAINING CENTER",
    state_providence: "TX",
  },
  {
    country_code: "USA",
    training_center_id: "WAC",
    training_center_name: "WASHINGTON COUNTY FAIRGROUNDS",
    state_providence: "UT",
  },
  {
    country_code: "USA",
    training_center_id: "WCR",
    training_center_name: "WINDING CREEK FARMS",
    state_providence: "MD",
  },
  {
    country_code: "USA",
    training_center_id: "WCT",
    training_center_name: "WEBB CARROLL TRAINING CENTER",
    state_providence: "SC",
  },
  {
    country_code: "USA",
    training_center_id: "WDB",
    training_center_name: "WOODBROOK FARM",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "WFR",
    training_center_name: "WILD FALCON RANCH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "WHL",
    training_center_name: "WHEELER TRAINING STATION",
    state_providence: "IN",
  },
  {
    country_code: "USA",
    training_center_id: "WHT",
    training_center_name: "WHISPER HILL TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "WKY",
    training_center_name: "WEST KY THOROUGHBRED TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "WLN",
    training_center_name: "WALNUT HALL",
    state_providence: "VA",
  },
  {
    country_code: "USA",
    training_center_id: "WM",
    training_center_name: "WILLISTON MILE",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "WND",
    training_center_name: "WINDING OAKS FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "WOD",
    training_center_name: "WOODSIDE RANCH",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "WRC",
    training_center_name: "W R TRAINING CENTER",
    state_providence: "OK",
  },
  {
    country_code: "USA",
    training_center_id: "WRT",
    training_center_name: "WINDY RIDGE TRAINING CENTER",
    state_providence: "WA",
  },
  {
    country_code: "USA",
    training_center_id: "WSF",
    training_center_name: "WESFIELD FARM",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "WSR",
    training_center_name: "WINSTAR TRAINING CENTER",
    state_providence: "KY",
  },
  {
    country_code: "USA",
    training_center_id: "WST",
    training_center_name: "WESTAMPTON FARMS",
    state_providence: "NJ",
  },
  {
    country_code: "USA",
    training_center_id: "WTC",
    training_center_name: "WEBSTER TRAINING CENTER",
    state_providence: "FL",
  },
  {
    country_code: "USA",
    training_center_id: "WTT",
    training_center_name: "WILDCAT TRAINING CENTER",
    state_providence: "FL",
  },
];
